import {createClient} from '@supabase/supabase-js';
import {config} from './config.js';
import {mountReader} from './reader.js';
import {HighlightSync} from './sync.js';
import body from './reader-body.html';
const app=document.getElementById('app');let client,reader,sync,user,works;
function login(message=''){app.innerHTML=`<main class="login"><div class="eyebrow">나만의 고전문학 서재</div><h1>고전 읽기</h1><p>같은 계정으로 로그인하면 모든 기기에서 하이라이트가 이어집니다.</p><form id="loginForm"><label for="email">이메일</label><input id="email" type="email" autocomplete="email" required><button class="primary">로그인 링크 받기</button></form><p id="authError" role="status"></p></main>`;document.getElementById('authError').textContent=message;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const {error}=await client.auth.signInWithOtp({email:document.getElementById('email').value.trim(),options:{emailRedirectTo:location.origin+location.pathname,shouldCreateUser:false}});document.getElementById('authError').textContent=error?'로그인 링크를 보내지 못했습니다. 등록된 이메일인지 확인해 주세요.':'메일의 로그인 링크를 이 기기의 브라우저에서 열어 주세요.';button.disabled=false;};}
function status(text){const n=document.getElementById('cloudStatus');if(n)n.textContent=text;}
async function openReader(session){user=session.user;const membership=await client.from('reader_members').select('user_id').eq('user_id',user.id).maybeSingle();if(membership.error||!membership.data){login('이 계정의 서재 접근 권한이 아직 준비되지 않았습니다.');return;}
 const {data,error}=await client.storage.from('reader-private').download('catalogue.json');if(error){login('본문을 불러오지 못했습니다. 연결 상태를 확인한 뒤 다시 로그인해 주세요.');return;}
 works=JSON.parse(await data.text());app.innerHTML=body;let first=[];
 reader=mountReader(works,user.id,items=>{if(sync){if(sync.record(items))sync.flush();}else first=items;});
 const tools=document.createElement('div');tools.id='cloudTools';tools.innerHTML='<p id="cloudStatus" role="status">동기화 중</p><button id="syncNow">지금 동기화</button><button id="exportHighlights">표시 백업</button><button id="importHighlights">백업 가져오기</button><input id="importFile" type="file" accept="application/json,.json"><button id="signOut">로그아웃</button>';document.getElementById('settings').append(tools);
 document.querySelectorAll('#settings .hint').forEach((n,i)=>{if(i===1)n.textContent='하이라이트는 같은 계정의 기기끼리 동기화됩니다. 글자 크기와 화면 색은 기기마다 유지됩니다.';});
 sync=new HighlightSync({storage:localStorage,key:'reader-outbox-'+user.id,remote:{async push(operations){for(let i=0;i<operations.length;i+=200){const {error}=await client.rpc('reader_apply',{operations:operations.slice(i,i+200)});if(error)throw error;}},async pull(){let rows=[];for(let offset=0;;offset+=1000){const {data,error}=await client.from('reader_highlights').select('id,payload,deleted').order('id').range(offset,offset+999);if(error)throw error;rows.push(...data);if(data.length<1000)return rows;}}},onChange:items=>reader.receiveHighlights(items),onStatus:status});
 sync.remember(reader.getHighlights());await sync.flush();
 document.getElementById('syncNow').onclick=()=>sync.flush();
 document.getElementById('exportHighlights').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,highlights:reader.getHighlights()},null,2)],{type:'application/json'}));a.href=url;a.download='고전읽기_하이라이트.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 document.getElementById('importHighlights').onclick=()=>document.getElementById('importFile').click();
 document.getElementById('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10e6)throw Error();const raw=JSON.parse(await file.text()),items=raw.highlights;if(!Array.isArray(items)||items.length>10000)throw Error();const existing=new Map(reader.getHighlights().map(h=>[h.id,h]));for(const h of items){const w=works.find(w=>w.id===h.work),text=w?.body.map(b=>b.text).join('');if(!w||typeof h.id!=='string'||h.id.length>128||!Number.isInteger(h.start)||!Number.isInteger(h.end)||h.start<0||h.end<=h.start||text.slice(h.start,h.end)!==h.text||!['yellow','green','pink'].includes(h.color))throw Error();existing.set(h.id,{id:h.id,work:h.work,start:h.start,end:h.end,text:h.text,color:h.color});}reader.importHighlights([...existing.values()]);status('백업을 가져왔습니다. 동기화 중');await sync.flush();}catch{status('백업 파일을 확인해 주세요. 현재 표시는 유지됩니다.');}e.target.value='';};
 document.getElementById('signOut').onclick=async()=>{await sync.flush();if(Object.keys(sync.pending).length){status('아직 보내지 못한 표시가 있습니다. 연결 후 다시 로그아웃해 주세요.');return;}await client.auth.signOut();location.reload();};
 setInterval(()=>{if(!document.hidden)sync.flush();},15000);addEventListener('online',()=>sync.flush());document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync.flush();});
}
if(!config.url||!config.key){app.innerHTML='<main class="login"><h1>고전 읽기</h1><p>개인 서재 연결을 준비하고 있습니다.</p><p>아직 로그인과 기기 간 동기화를 사용할 수 없습니다.</p></main>';}else{client=createClient(config.url,config.key);const {data:{session},error}=await client.auth.getSession();if(session&&!error){try{await openReader(session);}catch{login('서재를 불러오지 못했습니다. 잠시 뒤 다시 시도해 주세요.');}}else login();}
