import {showLogin} from './login.js';
import {createClient} from '@supabase/supabase-js';
import {config} from './config.js';
import {mountReader} from './reader.js';
import {attachNotes} from './notes.js';
import {HighlightSync} from './sync.js';
import body from './reader-body.html';
const app=document.getElementById('app');let client,reader,sync,user,works,notes;
function login(message=''){showLogin({root:app,auth:client.auth,onSession:openReader,message,errorText:loginError});}
function loginError(error){const messages={otp_expired:'로그인 링크가 만료되었거나 이미 사용되었습니다.',invalid_credentials:'이메일 또는 비밀번호를 확인해 주세요. 비밀번호를 아직 설정하지 않았다면 로그인된 Safari의 ‘가 · 설정’에서 먼저 설정하세요.',weak_password:'비밀번호가 너무 단순합니다. 더 긴 비밀번호를 사용해 주세요.',over_email_send_rate_limit:'이메일 전송 횟수 제한에 도달했습니다. 잠시 후 다시 시도하거나 이미 받은 최신 메일을 확인해 주세요.',over_request_rate_limit:'요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.',email_address_not_authorized:'현재 메일 발송 설정에서 이 이메일로 보낼 수 없습니다. 로그인 설정을 확인해야 합니다.'};return messages[error.code]||'로그인 처리 중 오류가 발생했습니다: '+(error.code||error.message||'연결 오류');}
function status(text){const n=document.getElementById('cloudStatus');if(n)n.textContent=text;}
async function openReader(session){user=session.user;await client.rpc('reader_join');const membership=await client.from('reader_members').select('user_id').eq('user_id',user.id).maybeSingle();if(membership.error||!membership.data){login('로그인은 완료됐지만 서재에 등록된 이메일과 다릅니다.\n현재 로그인: '+user.email+'\n접근 계정 설정을 확인해야 합니다.');const switchAccount=document.createElement('button');switchAccount.textContent='다른 계정으로 로그인';switchAccount.onclick=async()=>{await client.auth.signOut();location.reload();};document.querySelector('.login').append(switchAccount);return;}
 const {data,error}=await client.storage.from('reader-private').download('catalogue-2027-sutuk-suwan-v1.json');if(error){login('본문을 불러오지 못했습니다. 연결 상태를 확인한 뒤 다시 로그인해 주세요.');return;}
 works=JSON.parse(await data.text());app.innerHTML=body;let first=[];
 notes=attachNotes({key:'reader-notes-'+user.id,remote:{async read(){const {data,error}=await client.from('reader_notes').select('work_id,body,version');if(error)throw error;return data;},async write(work,body,version){const {data,error}=await client.rpc('reader_save_note',{note_work:work,note_body:body,note_base:version});if(error)throw error;return data;}}});
 reader=mountReader(works,user.id,items=>{if(sync){if(sync.record(items))sync.flush();}else first=items;});
 const tools=document.createElement('div');tools.id='cloudTools';tools.innerHTML='<p id="cloudStatus" role="status">동기화 중</p><button id="syncNow">지금 동기화</button><button id="exportHighlights">표시 백업</button><button id="importHighlights">백업 가져오기</button><input id="importFile" type="file" accept="application/json,.json"><button id="signOut">로그아웃</button>';document.getElementById('settings').append(tools);
 const pw=document.createElement('details');pw.innerHTML='<summary>리더 비밀번호 설정</summary><p class="hint">한 번 설정하면 다른 기기에서도 이메일과 이 비밀번호로 로그인할 수 있습니다. Supabase 관리용 비밀번호와는 별개입니다.</p><form id="setPasswordForm"><label for="newPassword">새 비밀번호 (10자 이상)</label><input id="newPassword" type="password" minlength="10" autocomplete="new-password" required><label for="confirmPassword">비밀번호 확인</label><input id="confirmPassword" type="password" minlength="10" autocomplete="new-password" required><button>비밀번호 저장</button><p id="passwordStatus" role="status"></p></form>';tools.append(pw);
 document.getElementById('setPasswordForm').onsubmit=async e=>{e.preventDefault();const one=document.getElementById('newPassword'),two=document.getElementById('confirmPassword'),message=document.getElementById('passwordStatus'),button=e.target.querySelector('button');if(one.value!==two.value){message.textContent='두 비밀번호가 다릅니다.';return;}button.disabled=true;try{const {error}=await client.auth.updateUser({password:one.value});if(error)throw error;one.value='';two.value='';message.textContent='저장했습니다. 다음부터 이메일과 비밀번호로 로그인할 수 있습니다.';}catch(error){message.textContent=loginError(error);}finally{button.disabled=false;}};

 document.querySelectorAll('#settings .hint').forEach((n,i)=>{if(i===1)n.textContent='하이라이트와 작품별 메모는 같은 계정의 기기끼리 동기화됩니다. 글자 크기와 화면 색은 기기마다 유지됩니다.';});
 sync=new HighlightSync({storage:localStorage,key:'reader-outbox-'+user.id,remote:{async push(operations){for(let i=0;i<operations.length;i+=200){const {error}=await client.rpc('reader_apply',{operations:operations.slice(i,i+200)});if(error)throw error;}},async pull(){let rows=[];for(let offset=0;;offset+=1000){const {data,error}=await client.from('reader_highlights').select('id,payload,deleted').order('id').range(offset,offset+999);if(error)throw error;rows.push(...data);if(data.length<1000)return rows;}}},onChange:items=>reader.receiveHighlights(items),onStatus:status});
 sync.remember(reader.getHighlights());await sync.flush();
 document.getElementById('syncNow').onclick=()=>{sync.flush();notes.flush();};
 document.getElementById('exportHighlights').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,highlights:reader.getHighlights()},null,2)],{type:'application/json'}));a.href=url;a.download='고전읽기_하이라이트.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 document.getElementById('importHighlights').onclick=()=>document.getElementById('importFile').click();
 document.getElementById('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10e6)throw Error();const raw=JSON.parse(await file.text()),items=raw.highlights;if(!Array.isArray(items)||items.length>10000)throw Error();const existing=new Map(reader.getHighlights().map(h=>[h.id,h]));for(const h of items){const w=works.find(w=>w.id===h.work),text=w?.body.map(b=>b.text).join('');if(!w||typeof h.id!=='string'||h.id.length>128||!Number.isInteger(h.start)||!Number.isInteger(h.end)||h.start<0||h.end<=h.start||text.slice(h.start,h.end)!==h.text||!['yellow','green','pink'].includes(h.color))throw Error();existing.set(h.id,{id:h.id,work:h.work,start:h.start,end:h.end,text:h.text,color:h.color});}reader.importHighlights([...existing.values()]);status('백업을 가져왔습니다. 동기화 중');await sync.flush();}catch{status('백업 파일을 확인해 주세요. 현재 표시는 유지됩니다.');}e.target.value='';};
 document.getElementById('signOut').onclick=async()=>{await sync.flush();await notes.flush();if(Object.keys(sync.pending).length||Object.values(notes.notes).some(n=>n.dirty||n.conflict)){status('아직 보내지 못한 표시가 있습니다. 연결 후 다시 로그아웃해 주세요.');return;}await client.auth.signOut();location.reload();};
 setInterval(()=>{if(!document.hidden)sync.flush();},15000);addEventListener('online',()=>sync.flush());document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync.flush();});
}
if(!config.url||!config.key){app.innerHTML='<main class="login"><h1>고전 읽기</h1><p>개인 서재 연결을 준비하고 있습니다.</p><p>아직 로그인과 기기 간 동기화를 사용할 수 없습니다.</p></main>';}else{client=createClient(config.url,config.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session},error}=await client.auth.getSession();if(session&&!error){try{await openReader(session);}catch{login('서재를 불러오지 못했습니다. 잠시 뒤 다시 시도해 주세요.');}}else login();}
