export function showLogin({root,auth,onSession,message='',errorText}){
 root.innerHTML=`<main class="login"><div class="eyebrow">나만의 고전문학 서재</div><h1>고전 읽기</h1><p>홈 화면에서도 이메일과 리더 비밀번호로 바로 로그인하세요.</p><form id="passwordForm"><label for="email">이메일</label><input id="email" type="email" autocomplete="username" required><label for="password">리더 비밀번호</label><input id="password" type="password" autocomplete="current-password" required><button class="primary">로그인</button></form><p class="hint">비밀번호가 아직 없다면, 작품 목록이 열리는 Safari에서 ‘가 · 설정 → 리더 비밀번호 설정’을 먼저 이용하세요. Supabase나 데이터베이스 비밀번호와는 별개입니다.</p><p class="hint">로그인은 이 기기에 유지됩니다. 웹사이트 데이터를 지우거나 로그아웃하면 다시 로그인해야 합니다.</p><details id="emailLogin"><summary>처음 로그인 / 비밀번호를 잊었어요</summary><p class="hint">아직 로그인된 화면이 없다면 이메일 링크로 Safari에 로그인한 뒤 비밀번호를 설정하세요. 그다음 홈 화면으로 돌아와 비밀번호로 로그인하면 됩니다.</p><form id="loginForm"><button id="sendLink">이메일 로그인 링크 받기</button></form></details><p id="authError" role="status"></p></main>`;
 const email=root.querySelector('#email'),status=root.querySelector('#authError'),send=root.querySelector('#sendLink');
 try{email.value=localStorage.getItem('reader-login-email')||'';}catch{}
 status.textContent=message;
 const readEmail=()=>{if(!email.reportValidity())return null;const value=email.value.trim().toLowerCase();try{localStorage.setItem('reader-login-email',value);}catch{}return value;};
 let resendAt=0,sending=false;try{resendAt=Number(localStorage.getItem('reader-resend-at'))||0;}catch{}
 function countdown(){if(!send.isConnected){clearInterval(timer);return;}const sec=Math.ceil((resendAt-Date.now())/1000);send.disabled=sending||sec>0;send.textContent=sending?'보내는 중…':sec>0?`다시 받기 (${sec}초)`:'이메일 로그인 링크 받기';}
 const timer=setInterval(countdown,1000);countdown();
 root.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const value=readEmail();if(!value)return;sending=true;countdown();try{const {error}=await auth.signInWithOtp({email:value,options:{shouldCreateUser:false,emailRedirectTo:location.origin+location.pathname}});if(error)throw error;resendAt=Date.now()+60000;try{localStorage.setItem('reader-resend-at',String(resendAt));}catch{}status.textContent='메일 링크로 로그인한 뒤 ‘가 · 설정’에서 리더 비밀번호를 설정하세요.';}catch(error){status.textContent=errorText(error);}finally{sending=false;countdown();}};
 root.querySelector('#passwordForm').onsubmit=async e=>{e.preventDefault();const value=readEmail();if(!value)return;const button=e.target.querySelector('button'),input=root.querySelector('#password');button.disabled=true;status.textContent='로그인 확인 중…';try{const {data,error}=await auth.signInWithPassword({email:value,password:input.value});if(error)throw error;if(!data.session)throw Error('로그인 정보를 받지 못했습니다.');input.value='';await onSession(data.session);}catch(error){status.textContent=errorText(error);}finally{if(button.isConnected)button.disabled=false;}};
}
