export class NotesStore {
 constructor({storage,key,remote,onChange=()=>{}}){Object.assign(this,{storage,key,remote,onChange});this.notes=JSON.parse(storage.getItem(key)||'{}');this.busy=false;this.failure=false;}
 get(id){return this.notes[id]||{body:'',version:0,dirty:false};}
 save(){try{this.storage.setItem(this.key,JSON.stringify(this.notes));this.storageFailed=false;}catch{this.storageFailed=true;}this.onChange();}
 edit(id,body){const n=this.get(id);this.notes[id]={...n,body,dirty:!!this.remote,tick:(n.tick||0)+1};this.save();}
 resolve(id,body){const n=this.get(id);this.notes[id]={...n,body,version:n.conflict.version,conflict:null,dirty:true,tick:(n.tick||0)+1};this.save();}
 async flush(){if(!this.remote||this.busy)return;this.busy=true;try{for(const [id,n]of Object.entries(this.notes)){if(!n.dirty||n.conflict)continue;const sent={...n};const r=await this.remote.write(id,sent.body,sent.version);const now=this.get(id);if(r.conflict){this.notes[id]={...now,conflict:r.note};}else{this.notes[id]={...now,version:r.note.version,dirty:now.tick!==sent.tick};}this.save();}const rows=await this.remote.read();for(const r of rows){const n=this.get(r.work_id);if(!n.dirty&&!n.conflict)this.notes[r.work_id]={body:r.body,version:r.version,dirty:false,tick:n.tick||0};}this.failure=false;this.save();}catch{this.failure=true;this.onChange();}finally{this.busy=false;}}
}
export function attachNotes({key,remote=null}){
 let active=null,timer;const store=new NotesStore({storage:localStorage,key,remote,onChange:refresh});
 function refresh(){if(!active)return;const input=document.getElementById('noteBody'),status=document.getElementById('noteStatus'),box=document.getElementById('noteConflict');if(!input||!status)return;const n=store.get(active);if(input.value!==n.body)input.value=n.body;status.textContent=store.storageFailed?'기기에 저장하지 못했습니다. 메모를 복사해 보관해 주세요.':n.conflict?'다른 기기에서 수정한 메모가 있습니다. 두 내용을 확인해 주세요.':n.dirty?(store.failure?'기기에 저장됨 · 연결되면 동기화':'기기에 저장됨 · 동기화 대기'):remote?'저장됨 · 다른 기기와 동기화':'이 기기에 저장됨';box.hidden=!n.conflict;if(n.conflict)document.getElementById('otherNote').textContent=n.conflict.body||'(빈 메모)';document.getElementById('noteCount').textContent=n.body.length.toLocaleString()+' / 50,000자';}
 function mount(w){active=w.id;const section=document.createElement('section');section.className='bottom-section';section.id='workNotes';section.innerHTML='<h2 class="section-title"><span class="num">07</span>내 메모</h2><p class="source">인물, 사건 흐름, 헷갈리는 부분을 자유롭게 정리하세요.</p><label class="note-label" for="noteBody">이 작품의 정리</label><textarea id="noteBody" maxlength="50000" placeholder="이 작품에서 기억할 내용…"></textarea><div class="note-meta"><span id="noteStatus" role="status"></span><span id="noteCount"></span></div><div id="noteConflict" hidden><h3>다른 기기의 메모</h3><pre id="otherNote"></pre><p class="source">위 입력칸에 남길 내용을 정리한 뒤 아래 버튼을 누르세요.</p><button id="mergeNotes">두 메모 합치기</button> <button id="keepNote">위 입력칸 내용으로 저장</button></div><button id="downloadNote">메모 파일 저장</button>';
 const footer=document.querySelector('#main footer');footer.before(section);const jump=document.createElement('button');jump.textContent='내 메모';jump.id='toNotes';jump.onclick=()=>{section.scrollIntoView();};document.querySelector('#main .actions').append(jump);
 const input=document.getElementById('noteBody');input.oninput=()=>{store.edit(active,input.value);clearTimeout(timer);timer=setTimeout(()=>store.flush(),800);};document.getElementById('mergeNotes').onclick=()=>{const n=store.get(active);const merged=n.body+'\n\n── 다른 기기의 메모 ──\n'+n.conflict.body;if(merged.length>50000){document.getElementById('noteStatus').textContent='합친 메모가 50,000자를 넘습니다. 위 입력칸에서 내용을 줄여 주세요.';return;}store.resolve(active,merged);store.flush();};document.getElementById('keepNote').onclick=()=>{store.resolve(active,input.value);store.flush();};document.getElementById('downloadNote').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([store.get(active).body],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=w.title+'_메모.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};refresh();store.flush();}
 addEventListener('reader:work',e=>mount(e.detail));if(remote){store.flush();setInterval(()=>{if(!document.hidden)store.flush();},15000);addEventListener('online',()=>store.flush());document.addEventListener('visibilitychange',()=>{if(!document.hidden)store.flush();});}return store;
}
